SECTION "Map Scripts 1", ROMX
INCLUDE "maps/ApartmentsF1.ctf"
INCLUDE "maps/ApartmentsF2.ctf"
INCLUDE "maps/ApartmentsF3.ctf"
INCLUDE "maps/SoutherlyHouse.ctf"
INCLUDE "maps/SoutherlyHouse2.ctf"
INCLUDE "maps/TunodWaterway.ctf"
INCLUDE "maps/TradeCenter.ctf"
INCLUDE "maps/TimeCapsule.ctf"
INCLUDE "maps/BattleArcadeBattleroom.ctf"
INCLUDE "maps/SaffronCopycatsHouse.ctf"
INCLUDE "maps/Route49Gate.ctf"
INCLUDE "maps/Route78EastExit.ctf"
INCLUDE "maps/Route81Eastgate.ctf"
INCLUDE "maps/Route81Goodrod.ctf"
INCLUDE "maps/Route86UndergroundPath.ctf"
INCLUDE "maps/FarawayIslandOutside.ctf"
INCLUDE "maps/FarawayIslandInside.ctf"
INCLUDE "maps/PhloxEntry.ctf"

SECTION "Map Scripts 2", ROMX
INCLUDE "maps/AzaleaTown.ctf"
INCLUDE "maps/AzaleaPokecenter.ctf"
INCLUDE "maps/AzaleaMart.ctf"
INCLUDE "maps/AzaleaGym.ctf"
INCLUDE "maps/AzaleaCharcoal.ctf"
INCLUDE "maps/AzaleaKurt.ctf"
INCLUDE "maps/AzaleaKurtBasement.ctf"
INCLUDE "maps/IlexForest.ctf"
INCLUDE "maps/GoldenrodCity.ctf"
INCLUDE "maps/GoldenrodCape.ctf"
INCLUDE "maps/GoldenrodCapeGate.ctf"
INCLUDE "maps/GoldenrodPokecenter.ctf"
INCLUDE "maps/GoldenrodMart.ctf"
INCLUDE "maps/GoldenrodMagnetTrain.ctf"
INCLUDE "maps/GoldenrodGym.ctf"
INCLUDE "maps/GoldenrodUndergroundEntryA.ctf"
INCLUDE "maps/GoldenrodUndergroundEntryB.ctf"
INCLUDE "maps/GoldenrodUnderground.ctf"
INCLUDE "maps/GoldenrodSwitches.ctf"
INCLUDE "maps/GoldenrodStorage.ctf"
INCLUDE "maps/GoldenrodBill.ctf"
INCLUDE "maps/SaffronGates.ctf"
INCLUDE "maps/MtEmberEntrance.ctf"
INCLUDE "maps/MtEmberRoom2.ctf"
INCLUDE "maps/AcaniaHouse.ctf"
INCLUDE "maps/AcaniaTM63.ctf"
INCLUDE "maps/RuinsEntry.ctf"
INCLUDE "maps/ProvincialPark.ctf"
INCLUDE "maps/PhaceliaWestExit.ctf"
INCLUDE "maps/SaxifrageWardensHouse.ctf"
INCLUDE "maps/Route34.ctf"
INCLUDE "maps/Route75.ctf"
INCLUDE "maps/Route76.ctf"
INCLUDE "maps/Route77.ctf"
INCLUDE "maps/Route77Pokecenter.ctf"
INCLUDE "maps/Route77DaycareHouse.ctf"
INCLUDE "maps/Route77DaycareGarden.ctf"

SECTION "Map Scripts 3", ROMX
INCLUDE "maps/IntroOutside.ctf"
INCLUDE "maps/IntroCave.ctf"
INCLUDE "maps/CaperCity.ctf"
INCLUDE "maps/CaperPokecenter.ctf"
INCLUDE "maps/CaperMart.ctf"
INCLUDE "maps/CaperHouse.ctf"
INCLUDE "maps/OxalisCity.ctf"
INCLUDE "maps/OxalisGym.ctf"
INCLUDE "maps/OxalisMart.ctf"
INCLUDE "maps/TrainerHouse.ctf"
INCLUDE "maps/TrainerHouseB1F.ctf"
INCLUDE "maps/SpurgeCity.ctf"
; linked, do not separate
INCLUDE "maps/SpurgeGymB1F.ctf"
INCLUDE "maps/SpurgeGymB2F.ctf"
INCLUDE "maps/SpurgeGymB2FSidescroll.ctf"
; end linked section
INCLUDE "maps/HeathVillage.ctf"
INCLUDE "maps/HeathGym.ctf"
INCLUDE "maps/HeathGymGate.ctf"
INCLUDE "maps/HeathHouseTM30.ctf"
INCLUDE "maps/HeathHouseTM35.ctf"
INCLUDE "maps/HeathInn.ctf"
INCLUDE "maps/Apartments1C.ctf"
INCLUDE "maps/MtEmberRoom1.ctf"
INCLUDE "maps/BotanHouse.ctf"
INCLUDE "maps/Route55.ctf"
INCLUDE "maps/Route72Gate.ctf"
INCLUDE "maps/Route86DockExit.ctf"
INCLUDE "maps/MersonPokecenter.ctf"

SECTION "Map Scripts 4", ROMX
INCLUDE "maps/LaurelCity.ctf"
INCLUDE "maps/LaurelPokecenter.ctf"
INCLUDE "maps/LaurelMart.ctf"
INCLUDE "maps/LaurelGym.ctf"
INCLUDE "maps/LaurelLab.ctf"
INCLUDE "maps/LaurelNamerater.ctf"
INCLUDE "maps/LaurelStick.ctf"
INCLUDE "maps/LaurelGate.ctf"
INCLUDE "maps/MagikarpCavernsMain.ctf"
INCLUDE "maps/MagikarpCavernsRapids.ctf"
INCLUDE "maps/MagikarpCavernsEnd.ctf"
INCLUDE "maps/Route87.ctf"
INCLUDE "maps/ToreniaCity.ctf"
INCLUDE "maps/ToreniaPokecenter.ctf"
INCLUDE "maps/ToreniaMart.ctf"
INCLUDE "maps/ToreniaGym.ctf"
INCLUDE "maps/ToreniaMagnetTrain.ctf"
INCLUDE "maps/ToreniaPachisi.ctf"
INCLUDE "maps/ToreniaDrifloomTrade.ctf"
INCLUDE "maps/ToreniaCelebrity.ctf"
INCLUDE "maps/ToreniaGate.ctf"
INCLUDE "maps/PhaceliaCity.ctf"
INCLUDE "maps/PhaceliaPoliceF2.ctf"
INCLUDE "maps/PhaceliaPoliceF1.ctf"
INCLUDE "maps/PhaceliaEastExit.ctf"
INCLUDE "maps/PhaceliaPokecenter.ctf"
INCLUDE "maps/PhaceliaMart.ctf"
INCLUDE "maps/PhaceliaGym.ctf"
INCLUDE "maps/PhaceliaMoveDeleter.ctf"
INCLUDE "maps/PhaceliaSolrockTrade.ctf"
INCLUDE "maps/PhaceliaTM20.ctf"
INCLUDE "maps/SpurgeGymHouse.ctf"
INCLUDE "maps/HeathGymUnderground.ctf"

SECTION "Map Scripts 5", ROMX
INCLUDE "maps/Route34Gate.ctf"
INCLUDE "maps/SaxifragePokecenter.ctf"
INCLUDE "maps/SaxifrageMart.ctf"
INCLUDE "maps/SaxifrageExits.ctf"
INCLUDE "maps/SaxifrageGym.ctf"
INCLUDE "maps/PrisonB1F.ctf"
INCLUDE "maps/PrisonF1.ctf"
INCLUDE "maps/PrisonF2.ctf"
INCLUDE "maps/PrisonPaths.ctf"
INCLUDE "maps/PrisonBaths.ctf"
INCLUDE "maps/PrisonCafeteria.ctf"
INCLUDE "maps/PrisonElectricChair.ctf"
INCLUDE "maps/PrisonWorkout.ctf"
INCLUDE "maps/PrisonRoof.ctf"
INCLUDE "maps/PhloxMart.ctf"
INCLUDE "maps/PhloxPokecenter.ctf"
INCLUDE "maps/Orphanage.ctf"
INCLUDE "maps/BattleCenter.ctf"
INCLUDE "maps/PokecenterBackroom.ctf"
INCLUDE "maps/SoutherlyGym.ctf"
INCLUDE "maps/SpurgeGym1F.ctf"
INCLUDE "maps/HappinessRater.ctf"
INCLUDE "maps/MilosTowerClimb.ctf"

SECTION "Map Scripts 6", ROMX
INCLUDE "maps/PhloxTown.ctf"
INCLUDE "maps/PhloxLabB1F.ctf"
INCLUDE "maps/PhloxLab1F.ctf"
INCLUDE "maps/PhloxMyles.ctf"
INCLUDE "maps/AcaniaDocks.ctf"
INCLUDE "maps/FirelightF1.ctf"
INCLUDE "maps/MilosGreenOrb.ctf"
INCLUDE "maps/MilosRayquaza.ctf"
INCLUDE "maps/MoundUpperArea.ctf"
INCLUDE "maps/FirelightGroudon.ctf"
INCLUDE "maps/PhanceroRoom.ctf"
INCLUDE "maps/AcaniaLighthouseF1.ctf"
INCLUDE "maps/AcaniaLighthouseF2.ctf"
INCLUDE "maps/AcaniaGym.ctf"
INCLUDE "maps/HaywardCity.ctf"

SECTION "Map Scripts 7", ROMX
INCLUDE "maps/Route47.ctf"
INCLUDE "maps/Route52Gate.ctf"
INCLUDE "maps/Route55GateUnderground.ctf"
INCLUDE "maps/Route56.ctf"
INCLUDE "maps/Route57.ctf"
INCLUDE "maps/Route57Gym.ctf"
INCLUDE "maps/Route58.ctf"
INCLUDE "maps/Route58Gate.ctf"
INCLUDE "maps/Route59.ctf"
INCLUDE "maps/Route59Gate.ctf"
INCLUDE "maps/Route60.ctf"
INCLUDE "maps/Route60Gate.ctf"
INCLUDE "maps/Route61.ctf"
INCLUDE "maps/Route61GateSouth.ctf"
INCLUDE "maps/Route61GateNorth.ctf"
INCLUDE "maps/Route61House.ctf"
INCLUDE "maps/Route61House2.ctf"
INCLUDE "maps/Route62.ctf"
INCLUDE "maps/Route62Gate.ctf"
INCLUDE "maps/Route63.ctf"
INCLUDE "maps/Route64.ctf"
INCLUDE "maps/Route66.ctf"
INCLUDE "maps/Route67.ctf"
INCLUDE "maps/Route81Pokecenter.ctf"
INCLUDE "maps/SilphWarehouseF2.ctf"
INCLUDE "maps/PowerPlant.ctf"
INCLUDE "maps/MersonCaveB1F.ctf"
INCLUDE "maps/MersonCaveB2F.ctf"
INCLUDE "maps/MersonCaveB3F.ctf"
INCLUDE "maps/SilkTunnel1F.ctf"
INCLUDE "maps/SilkTunnelB1F.ctf"
INCLUDE "maps/SilkTunnelB2F.ctf"
INCLUDE "maps/SilkTunnelB3F.ctf"
INCLUDE "maps/SilkTunnelB4F.ctf"
INCLUDE "maps/CastroForest.ctf"
INCLUDE "maps/CastroForestGateSouth.ctf"
INCLUDE "maps/MtBoulderB1F.ctf"
INCLUDE "maps/MtBoulderB2F.ctf"
INCLUDE "maps/RijonUndergroundHorizontal.ctf"
INCLUDE "maps/RijonUndergroundVertical.ctf"
INCLUDE "maps/RijonHiddenBasement.ctf"
INCLUDE "maps/SenecaCavernsF1.ctf"
INCLUDE "maps/SenecaCavernsB1F.ctf"
INCLUDE "maps/SenecaCavernsB2F.ctf"
INCLUDE "maps/HauntedForestGate.ctf"
INCLUDE "maps/HauntedForest.ctf"
INCLUDE "maps/HauntedMansion.ctf"
INCLUDE "maps/DreamSequence.ctf"
INCLUDE "maps/DreamNewBark.ctf"
INCLUDE "maps/AcaniaPokecenter.ctf"
INCLUDE "maps/AcquaLabBasementPath.ctf"
INCLUDE "maps/BattleArcadeLobby.ctf"
INCLUDE "maps/PhloxLab2F.ctf"
INCLUDE "maps/MilosB2F.ctf"

SECTION "Map Scripts 8", ROMX
INCLUDE "maps/Route67Gate.ctf"
INCLUDE "maps/Route67Pokecenter.ctf"
INCLUDE "maps/Route67House.ctf"
INCLUDE "maps/Route69.ctf"
INCLUDE "maps/Route69IlkBrotherHouse.ctf"
INCLUDE "maps/HaywardEarthquakeLab.ctf"
INCLUDE "maps/HaywardHouse.ctf"
INCLUDE "maps/SoutherlyAirport.ctf"
INCLUDE "maps/MysteryZone.ctf"
INCLUDE "maps/MysteryZoneLeagueLobby.ctf"
INCLUDE "maps/MysteryZoneLeagueBrown.ctf"
INCLUDE "maps/MysteryZoneLeagueGold.ctf"
INCLUDE "maps/MysteryZoneLeagueRed.ctf"
INCLUDE "maps/MysteryZoneLeagueAirport.ctf"
INCLUDE "maps/SilkTunnelB5F.ctf"
INCLUDE "maps/FirelightItemRoom.ctf"

SECTION "Map Scripts 9", ROMX
INCLUDE "maps/Route78.ctf"
INCLUDE "maps/Route79.ctf"
INCLUDE "maps/Route80.ctf"
INCLUDE "maps/Route80Nobu.ctf"
INCLUDE "maps/Route81.ctf"
INCLUDE "maps/Route81Northgate.ctf"
INCLUDE "maps/Route82.ctf"
INCLUDE "maps/Route82Cave.ctf"
INCLUDE "maps/Route83.ctf"
INCLUDE "maps/Route84.ctf"
INCLUDE "maps/Route85.ctf"
INCLUDE "maps/Route86.ctf"
INCLUDE "maps/Route86Dock.ctf"
INCLUDE "maps/AcquaStart.ctf"
INCLUDE "maps/AcquaTutorial.ctf"
INCLUDE "maps/AcquaExitChamber.ctf"
INCLUDE "maps/AcquaHiTide.ctf"
INCLUDE "maps/AcquaMedTide.ctf"
INCLUDE "maps/AcquaLowTide.ctf"
INCLUDE "maps/AcquaRoom.ctf"
INCLUDE "maps/SpurgeGameCorner.ctf"
INCLUDE "maps/PhloxLab3F.ctf"
INCLUDE "maps/SaffronCity.ctf"
INCLUDE "maps/IlexForestGate.ctf"

SECTION "Map Scripts 10", ROMX
INCLUDE "maps/LaurelForestBeach.ctf"
INCLUDE "maps/LaurelForestCharizardCave.ctf"
INCLUDE "maps/LaurelForestLab.ctf"
INCLUDE "maps/MoundF1.ctf"
INCLUDE "maps/MoundB1F.ctf"
; linked, do not separate
INCLUDE "maps/MoundB2F.ctf"
INCLUDE "maps/MoundB3F.ctf"
; end linked section
INCLUDE "maps/ProvincialParkGate.ctf"
INCLUDE "maps/ProvincialParkContest.ctf"
INCLUDE "maps/MilosF1.ctf"
INCLUDE "maps/MilosB1F.ctf"
INCLUDE "maps/Route48.ctf"
INCLUDE "maps/Route50.ctf"
INCLUDE "maps/Route51.ctf"
INCLUDE "maps/Route52.ctf"
INCLUDE "maps/Route82Gate.ctf"
INCLUDE "maps/BotanCity.ctf"
INCLUDE "maps/BotanMagnetTrain.ctf"
INCLUDE "maps/SpurgeMart.ctf"
INCLUDE "maps/EagulouGymF1.ctf"

SECTION "Map Scripts 11", ROMX
INCLUDE "maps/MilosB2Fb.ctf"
INCLUDE "maps/RuinsOutside.ctf"
INCLUDE "maps/RuinsRoof.ctf"
INCLUDE "maps/FirelightPalletPathB1F.ctf"
INCLUDE "maps/FirelightPalletPath1F.ctf"
INCLUDE "maps/FirelightRooms.ctf"
INCLUDE "maps/CastroValley.ctf"
INCLUDE "maps/CastroGym.ctf"
INCLUDE "maps/CastroPokecenter.ctf"
INCLUDE "maps/CastroMansion.ctf"
INCLUDE "maps/CastroDock.ctf"
INCLUDE "maps/RijonLeagueYuki.ctf"
INCLUDE "maps/RijonLeagueSora.ctf"
INCLUDE "maps/RijonLeagueDaichi.ctf"
INCLUDE "maps/EagulouCity.ctf"
INCLUDE "maps/EagulouMart.ctf"
INCLUDE "maps/SilphCoB1F.ctf"
INCLUDE "maps/HeathGymHouse.ctf"
INCLUDE "maps/Route73Gate.ctf"
INCLUDE "maps/LaurelForestPokemonOnly.ctf"
INCLUDE "maps/SoutherlyMart.ctf"

SECTION "Map Scripts 12", ROMX
INCLUDE "maps/RuinsF1.ctf"
INCLUDE "maps/RuinsF4.ctf"
INCLUDE "maps/RuinsF5.ctf"
INCLUDE "maps/RuinsB1F.ctf"
INCLUDE "maps/Clathrite1F.ctf"
INCLUDE "maps/ClathriteB1F.ctf"
INCLUDE "maps/ClathriteB2F.ctf"
INCLUDE "maps/ClathriteKyogre.ctf"
INCLUDE "maps/NaljoBorderEast.ctf"
INCLUDE "maps/NaljoBorderWest.ctf"
INCLUDE "maps/NaljoBorderWarpRoom.ctf"
INCLUDE "maps/LongTunnelPath.ctf"
INCLUDE "maps/LongTunnelSidescroll.ctf"
INCLUDE "maps/SeashoreCity.ctf"
INCLUDE "maps/SeashoreGym.ctf"
INCLUDE "maps/SeashoreMura.ctf"
INCLUDE "maps/BrownsHouseF1.ctf"
INCLUDE "maps/BrownsHouseF2.ctf"
INCLUDE "maps/GravelTown.ctf"
INCLUDE "maps/GravelMart.ctf"
INCLUDE "maps/JensLab.ctf"
INCLUDE "maps/MersonCity.ctf"
INCLUDE "maps/MersonGym.ctf"
INCLUDE "maps/MersonMart.ctf"
INCLUDE "maps/MersonHouse.ctf"
INCLUDE "maps/MersonBirdHouse.ctf"
INCLUDE "maps/LaurelForestMain.ctf"
INCLUDE "maps/HauntedMansionBasement.ctf"
INCLUDE "maps/Route69Gate.ctf"
INCLUDE "maps/Route70.ctf"
INCLUDE "maps/Route71.ctf"
INCLUDE "maps/Route71b.ctf"
INCLUDE "maps/Route72.ctf"
INCLUDE "maps/Route73.ctf"

SECTION "Map Scripts 13", ROMX
INCLUDE "maps/MersonGoldTokenExchange.ctf"
INCLUDE "maps/HaywardMartF1.ctf"
INCLUDE "maps/HaywardMartF2.ctf"
INCLUDE "maps/HaywardMartF3.ctf"
INCLUDE "maps/HaywardMartF4.ctf"
INCLUDE "maps/HaywardMartF5.ctf"
INCLUDE "maps/HaywardMartElevator.ctf"
INCLUDE "maps/HaywardMartF6.ctf"
INCLUDE "maps/HaywardPokecenter.ctf"
INCLUDE "maps/HaywardMawile.ctf"
INCLUDE "maps/OwsauriCity.ctf"
INCLUDE "maps/OwsauriGym.ctf"
INCLUDE "maps/OwsauriGameCorner.ctf"
INCLUDE "maps/OwsauriMart.ctf"
INCLUDE "maps/OwsauriPokecenter.ctf"
INCLUDE "maps/OwsauriNamerater.ctf"
INCLUDE "maps/OwsauriHouse.ctf"
INCLUDE "maps/OwsauriStatEXP.ctf"
INCLUDE "maps/MoragaTown.ctf"
INCLUDE "maps/MoragaGym.ctf"
INCLUDE "maps/MoragaDiner.ctf"
INCLUDE "maps/MoragaGateUnderground.ctf"
INCLUDE "maps/MoragaMart.ctf"
INCLUDE "maps/MoragaPokecenter.ctf"
INCLUDE "maps/MoragaHouse.ctf"
INCLUDE "maps/MoragaMoveRelearner.ctf"
INCLUDE "maps/JaeruCity.ctf"
INCLUDE "maps/JaeruGym.ctf"
INCLUDE "maps/JaeruGate.ctf"
INCLUDE "maps/JaeruMart.ctf"
INCLUDE "maps/JaeruGoldTokenVendor.ctf"
INCLUDE "maps/BotanMart.ctf"
INCLUDE "maps/BotanPokecenter.ctf"
INCLUDE "maps/BotanPachisi.ctf"
INCLUDE "maps/CastroGate.ctf"
INCLUDE "maps/FirelightMinecart.ctf"

SECTION "Map Scripts 14", ROMX
INCLUDE "maps/Route52GateUnderground.ctf"
INCLUDE "maps/Route52House.ctf"
INCLUDE "maps/Route53.ctf"
INCLUDE "maps/Route54.ctf"
INCLUDE "maps/Route56Gate.ctf"
INCLUDE "maps/Route56GateUnderground.ctf"
INCLUDE "maps/SilphWarehouseF1.ctf"
INCLUDE "maps/SilphWarehouseB1F.ctf"
INCLUDE "maps/Apartments2D.ctf"
INCLUDE "maps/SeviiIsland1.ctf"
INCLUDE "maps/SeviiIsland2.ctf"
INCLUDE "maps/SeviiIsland3.ctf"
INCLUDE "maps/EmberBrook.ctf"
INCLUDE "maps/GoldenrodMartB1F.ctf"

SECTION "Map Scripts 15", ROMX
INCLUDE "maps/CastroTyrogueTrade.ctf"
INCLUDE "maps/EagulouPark3.ctf"
INCLUDE "maps/SoutherlyBattleHouse.ctf"
INCLUDE "maps/SoutherlyPokecenter.ctf"
INCLUDE "maps/OxalisSalon.ctf"
INCLUDE "maps/PhloxBingo.ctf"
INCLUDE "maps/RijonLeagueOutside.ctf"
INCLUDE "maps/RijonLeagueInside.ctf"
INCLUDE "maps/RijonLeagueParty.ctf"
INCLUDE "maps/RijonLeagueChampionRoom.ctf"
INCLUDE "maps/PrisonContainment.ctf"
INCLUDE "maps/Route49.ctf"
INCLUDE "maps/Route50Gate.ctf"

SECTION "Map Scripts small 1", ROMX
INCLUDE "maps/RuinsF3.ctf"

SECTION "Map Scripts small 2", ROMX
INCLUDE "maps/GoldenrodGameCorner.ctf"
INCLUDE "maps/GoldenrodHappinessMoveTeacher.ctf"
INCLUDE "maps/SaffronPokecenter.ctf"
INCLUDE "maps/SilphCo.ctf"
INCLUDE "maps/AcquaPhloxEntrance.ctf"
INCLUDE "maps/Route77Jewelers.ctf"
INCLUDE "maps/Apartments1B.ctf"

SECTION "Map Scripts small 3", ROMX
INCLUDE "maps/JaeruPokecenter.ctf"
INCLUDE "maps/SaffronMart.ctf"
INCLUDE "maps/SaffronFightingDojo.ctf"

SECTION "Map Scripts small 4", ROMX
INCLUDE "maps/SaxifrageIsland.ctf"
INCLUDE "maps/HeathHouseWeaver.ctf"
INCLUDE "maps/SouthSoutherly.ctf"
INCLUDE "maps/SaffronMagnetTrain.ctf"
INCLUDE "maps/EmberBrookGate.ctf"

SECTION "Map Scripts small 5", ROMX
INCLUDE "maps/AcaniaMart.ctf"
INCLUDE "maps/SpurgePokecenter.ctf"

SECTION "Map Scripts small 6", ROMX
INCLUDE "maps/SaffronGym.ctf"
INCLUDE "maps/MtEmber.ctf"
INCLUDE "maps/CastroDockPath.ctf"
INCLUDE "maps/LaurelForestGates.ctf"

SECTION "Map Scripts small 7", ROMX
INCLUDE "maps/Route65.ctf"
INCLUDE "maps/Route68.ctf"
INCLUDE "maps/Route74.ctf"
INCLUDE "maps/Route82Monkey.ctf"
INCLUDE "maps/RijonLeagueLance.ctf"
INCLUDE "maps/MersonHouse2.ctf"
INCLUDE "maps/SaffronMrPsychic.ctf"
INCLUDE "maps/RuinsF2.ctf"

SECTION "Map Scripts small 8", ROMX
INCLUDE "maps/EagulouParkGate.ctf"

SECTION "Map Scripts small 9", ROMX
INCLUDE "maps/IlksLab.ctf"
INCLUDE "maps/SoutherlyCity.ctf"
INCLUDE "maps/HeathGate.ctf"
INCLUDE "maps/OxalisPokecenter.ctf"

SECTION "Map Scripts small 10", ROMX
INCLUDE "maps/CastroMart.ctf"

SECTION "Map Scripts small 11", ROMX
INCLUDE "maps/SpurgeHouse.ctf"

SECTION "Map Scripts small 12", ROMX
INCLUDE "maps/EagulouPark2.ctf"
INCLUDE "maps/EagulouGymB1F.ctf"
INCLUDE "maps/EagulouPokecenter.ctf"
INCLUDE "maps/EagulouPark1.ctf"
INCLUDE "maps/RijonLeagueMura.ctf"
INCLUDE "maps/CastroSuperRod.ctf"

SECTION "Battle Tower Map Scripts", ROMX
; THESE MUST ALL BE IN THE SAME BANK
INCLUDE "maps/BattleTowerEntrance.ctf"
INCLUDE "maps/BattleTowerElevator.ctf"
INCLUDE "maps/BattleTowerHallway.ctf"
INCLUDE "maps/BattleTowerBattleRoom.ctf"
; please stop adding non-battle-tower scripts here, add them to Map Scripts 3 if you must
