	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 32
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, BROWN, TEXT, TEXT, TEXT
