	tilepal 0, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 32
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, ROOF, ROOF, TEXT, TEXT, TEXT, TEXT
