	tilepal 0, GREEN, BROWN, BROWN, GREEN, YELLOW, GREEN, BROWN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, WATER, GREEN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, GREEN, GREEN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN

rept 32
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, TEXT, TEXT
