	tilepal 0, BROWN, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 0, WATER, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, BROWN, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, WATER, WATER, RED, RED, RED, RED, WATER
	tilepal 0, BROWN, YELLOW, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, RED, RED, RED, RED, GRAY, RED, WATER

rept 32
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, WATER, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BROWN
	tilepal 1, BROWN, YELLOW, YELLOW, ROOF, RED, RED, RED, RED
