	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, RED, GREEN, GREEN, GREEN, GREEN, WATER, WATER, WATER
	tilepal 0, WATER, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
