	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED
	tilepal 0, RED, RED, RED, GREEN, GREEN, WATER, WATER, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED
	tilepal 0, RED, RED, RED, GREEN, GREEN, WATER, WATER, YELLOW

rept 32
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, BROWN, BROWN, ROOF, ROOF, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, YELLOW, YELLOW, BROWN, BROWN, ROOF, ROOF, TEXT, TEXT
