	const_def
	const START_MENU_DEX
	const START_MENU_PKMN
	const START_MENU_PACK
	const START_MENU_MAP
	const START_MENU_STATUS
	const START_MENU_SAVE
	const START_MENU_OPTION
	const START_MENU_EXIT
	const START_MENU_TREASURE_BAG

	const_def
	const MENU_EXIT_RETURN
	const MENU_EXIT_ALL
	const MENU_EXIT_FUNCTION
	const MENU_EXIT_SCRIPT_CLOSE_TEXT
	const MENU_EXIT_SCRIPT
	const MENU_EXIT_RETURN_END
	const MENU_EXIT_RETURN_REDRAW

DEBUG_FLAG_SET       EQU $d7 ; +
DEBUG_FLAG_CLEAR     EQU $e3 ; -
DEBUG_CURSOR_DOWN    EQU $ee ; ▼
DEBUG_CURSOR_RIGHT   EQU $ed ; ▶
DEBUG_LEFT_ARROW     EQU $df ; <LEFT>
DEBUG_RIGHT_ARROW    EQU $eb ; <RIGHT>
