	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum fastcurrent
	enum merchandiseshelf
	enum townmap
	enum mining
	enum jumpingshoes
	enum smelting
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum elevatorbutton
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
	enum cagekeydoor
	enum trade
	enum qrcode
